//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.2.0
//     from Assets/InputControls/InputMaster.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputMaster : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputMaster()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputMaster"",
    ""maps"": [
        {
            ""name"": ""DepthRay"",
            ""id"": ""23cd7bf6-888a-43e4-bb0a-6c434504f6f8"",
            ""actions"": [
                {
                    ""name"": ""CastRay"",
                    ""type"": ""Value"",
                    ""id"": ""d3e0bbea-c84d-4334-8727-90bdce684e4e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MoveSphere"",
                    ""type"": ""Value"",
                    ""id"": ""7762bf7b-b0d7-4f25-ad38-31663ddc3cc2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e1be571b-5d74-410c-9174-e33b00142517"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CastRay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ae281d4e-9f79-4291-a368-68a1bbaf250b"",
                    ""path"": ""<XRController>{RightHand}/triggerPressed"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CastRay"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""ArrowKeys"",
                    ""id"": ""45b61d09-b1bd-41fc-9190-0e9d5c96256f"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSphere"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""f2b3cfb0-e9bc-45e3-b4ea-f5411fc23b4a"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSphere"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""208880ff-49d9-45c8-8397-64399ee775a6"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSphere"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""91b35a12-a6ac-48e0-b13b-2673254ce82a"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSphere"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""902a8bcd-2dd9-44c4-b1cb-cbc8aaaa43ac"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSphere"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""86963bd1-8d9a-4643-8dfe-6c666968dbc8"",
                    ""path"": ""<XRController>{RightHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveSphere"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // DepthRay
        m_DepthRay = asset.FindActionMap("DepthRay", throwIfNotFound: true);
        m_DepthRay_CastRay = m_DepthRay.FindAction("CastRay", throwIfNotFound: true);
        m_DepthRay_MoveSphere = m_DepthRay.FindAction("MoveSphere", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // DepthRay
    private readonly InputActionMap m_DepthRay;
    private IDepthRayActions m_DepthRayActionsCallbackInterface;
    private readonly InputAction m_DepthRay_CastRay;
    private readonly InputAction m_DepthRay_MoveSphere;
    public struct DepthRayActions
    {
        private @InputMaster m_Wrapper;
        public DepthRayActions(@InputMaster wrapper) { m_Wrapper = wrapper; }
        public InputAction @CastRay => m_Wrapper.m_DepthRay_CastRay;
        public InputAction @MoveSphere => m_Wrapper.m_DepthRay_MoveSphere;
        public InputActionMap Get() { return m_Wrapper.m_DepthRay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(DepthRayActions set) { return set.Get(); }
        public void SetCallbacks(IDepthRayActions instance)
        {
            if (m_Wrapper.m_DepthRayActionsCallbackInterface != null)
            {
                @CastRay.started -= m_Wrapper.m_DepthRayActionsCallbackInterface.OnCastRay;
                @CastRay.performed -= m_Wrapper.m_DepthRayActionsCallbackInterface.OnCastRay;
                @CastRay.canceled -= m_Wrapper.m_DepthRayActionsCallbackInterface.OnCastRay;
                @MoveSphere.started -= m_Wrapper.m_DepthRayActionsCallbackInterface.OnMoveSphere;
                @MoveSphere.performed -= m_Wrapper.m_DepthRayActionsCallbackInterface.OnMoveSphere;
                @MoveSphere.canceled -= m_Wrapper.m_DepthRayActionsCallbackInterface.OnMoveSphere;
            }
            m_Wrapper.m_DepthRayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @CastRay.started += instance.OnCastRay;
                @CastRay.performed += instance.OnCastRay;
                @CastRay.canceled += instance.OnCastRay;
                @MoveSphere.started += instance.OnMoveSphere;
                @MoveSphere.performed += instance.OnMoveSphere;
                @MoveSphere.canceled += instance.OnMoveSphere;
            }
        }
    }
    public DepthRayActions @DepthRay => new DepthRayActions(this);
    public interface IDepthRayActions
    {
        void OnCastRay(InputAction.CallbackContext context);
        void OnMoveSphere(InputAction.CallbackContext context);
    }
}
